Traceback (most recent call last):
  File "/opt/conda/envs/science/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/conda/envs/science/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/conda/envs/science/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/conda/envs/science/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/conda/envs/science/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/conda/envs/science/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/conda/envs/science/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
class AliasingImage:
    """
    Creates a aliasing illusion.
    """

    def __init__(self, size=(5, 5), depth=8):
        self.size = size
        self.depth = depth
        lx, ly = size
        x = np.arange(lx)
        y = np.arange(ly)
        self.f = 1.0
        self.df = 0.07
        self.X, self.Y = np.meshgrid(x, y)
        self.evolve()

    def evolve(self):
        """
        Randomizes the image
        """
        f = self.f
        self.image = np.cos(2 * f * self.X) * np.sin(2 * f * self.Y)
        self.f += self.df


ri = AliasingImage(size=(50, 50))


def updatefig(*args):
    ri.evolve()
    im.set_array(ri.image)
    return (im,)


fig, ax = plt.subplots()
ax.axis("off")
im = plt.imshow(ri.image, interpolation="nearest", cmap=cm.gray, animated=True)
anim = animation.FuncAnimation(fig, updatefig, frames=40, interval=50, blit=True)
# plt.show()
plt.close()
anim
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[6], line 40[0m
[1;32m     38[0m anim [38;5;241m=[39m animation[38;5;241m.[39mFuncAnimation(fig, updatefig, frames[38;5;241m=[39m[38;5;241m40[39m, interval[38;5;241m=[39m[38;5;241m50[39m, blit[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[1;32m     39[0m [38;5;66;03m# plt.show()[39;00m
[0;32m---> 40[0m [43mplt[49m[38;5;241;43m.[39;49m[43mclose[49m[43m([49m[43m)[49m
[1;32m     41[0m anim

File [0;32m/opt/conda/envs/science/lib/python3.10/site-packages/matplotlib/pyplot.py:1083[0m, in [0;36mclose[0;34m(fig)[0m
[1;32m   1081[0m         [38;5;28;01mreturn[39;00m
[1;32m   1082[0m     [38;5;28;01melse[39;00m:
[0;32m-> 1083[0m         [43m_pylab_helpers[49m[38;5;241;43m.[39;49m[43mGcf[49m[38;5;241;43m.[39;49m[43mdestroy[49m[43m([49m[43mmanager[49m[43m)[49m
[1;32m   1084[0m [38;5;28;01melif[39;00m fig [38;5;241m==[39m [38;5;124m'[39m[38;5;124mall[39m[38;5;124m'[39m:
[1;32m   1085[0m     _pylab_helpers[38;5;241m.[39mGcf[38;5;241m.[39mdestroy_all()

File [0;32m/opt/conda/envs/science/lib/python3.10/site-packages/matplotlib/_pylab_helpers.py:66[0m, in [0;36mGcf.destroy[0;34m(cls, num)[0m
[1;32m     64[0m [38;5;28;01mif[39;00m [38;5;28mhasattr[39m(manager, [38;5;124m"[39m[38;5;124m_cidgcf[39m[38;5;124m"[39m):
[1;32m     65[0m     manager[38;5;241m.[39mcanvas[38;5;241m.[39mmpl_disconnect(manager[38;5;241m.[39m_cidgcf)
[0;32m---> 66[0m [43mmanager[49m[38;5;241;43m.[39;49m[43mdestroy[49m[43m([49m[43m)[49m
[1;32m     67[0m [38;5;28;01mdel[39;00m manager, num

File [0;32m/opt/conda/envs/science/lib/python3.10/site-packages/matplotlib/backends/backend_nbagg.py:144[0m, in [0;36mFigureManagerNbAgg.destroy[0;34m(self)[0m
[1;32m    142[0m [38;5;28;01mfor[39;00m comm [38;5;129;01min[39;00m [38;5;28mlist[39m([38;5;28mself[39m[38;5;241m.[39mweb_sockets):
[1;32m    143[0m     comm[38;5;241m.[39mon_close()
[0;32m--> 144[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mclearup_closed[49m[43m([49m[43m)[49m

File [0;32m/opt/conda/envs/science/lib/python3.10/site-packages/matplotlib/backends/backend_nbagg.py:152[0m, in [0;36mFigureManagerNbAgg.clearup_closed[0;34m(self)[0m
[1;32m    148[0m [38;5;28mself[39m[38;5;241m.[39mweb_sockets [38;5;241m=[39m {socket [38;5;28;01mfor[39;00m socket [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39mweb_sockets
[1;32m    149[0m                     [38;5;28;01mif[39;00m socket[38;5;241m.[39mis_open()}
[1;32m    151[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m([38;5;28mself[39m[38;5;241m.[39mweb_sockets) [38;5;241m==[39m [38;5;241m0[39m:
[0;32m--> 152[0m     [43mCloseEvent[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mclose_event[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mcanvas[49m[43m)[49m[38;5;241;43m.[39;49m[43m_process[49m[43m([49m[43m)[49m

File [0;32m/opt/conda/envs/science/lib/python3.10/site-packages/matplotlib/backend_bases.py:1271[0m, in [0;36mEvent._process[0;34m(self)[0m
[1;32m   1269[0m [38;5;28;01mdef[39;00m [38;5;21m_process[39m([38;5;28mself[39m):
[1;32m   1270[0m [38;5;250m    [39m[38;5;124;03m"""Process this event on ``self.canvas``, then unset ``guiEvent``."""[39;00m
[0;32m-> 1271[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mcanvas[49m[38;5;241;43m.[39;49m[43mcallbacks[49m[38;5;241;43m.[39;49m[43mprocess[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mname[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[43m)[49m
[1;32m   1272[0m     [38;5;28mself[39m[38;5;241m.[39m_guiEvent_deleted [38;5;241m=[39m [38;5;28;01mTrue[39;00m

File [0;32m/opt/conda/envs/science/lib/python3.10/site-packages/matplotlib/cbook.py:303[0m, in [0;36mCallbackRegistry.process[0;34m(self, s, *args, **kwargs)[0m
[1;32m    301[0m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m [38;5;28;01mas[39;00m exc:
[1;32m    302[0m     [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mexception_handler [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[0;32m--> 303[0m         [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mexception_handler[49m[43m([49m[43mexc[49m[43m)[49m
[1;32m    304[0m     [38;5;28;01melse[39;00m:
[1;32m    305[0m         [38;5;28;01mraise[39;00m

File [0;32m/opt/conda/envs/science/lib/python3.10/site-packages/matplotlib/cbook.py:87[0m, in [0;36m_exception_printer[0;34m(exc)[0m
[1;32m     85[0m [38;5;28;01mdef[39;00m [38;5;21m_exception_printer[39m(exc):
[1;32m     86[0m     [38;5;28;01mif[39;00m _get_running_interactive_framework() [38;5;129;01min[39;00m [[38;5;124m"[39m[38;5;124mheadless[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m]:
[0;32m---> 87[0m         [38;5;28;01mraise[39;00m exc
[1;32m     88[0m     [38;5;28;01melse[39;00m:
[1;32m     89[0m         traceback[38;5;241m.[39mprint_exc()

File [0;32m/opt/conda/envs/science/lib/python3.10/site-packages/matplotlib/cbook.py:298[0m, in [0;36mCallbackRegistry.process[0;34m(self, s, *args, **kwargs)[0m
[1;32m    296[0m [38;5;28;01mif[39;00m func [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    297[0m     [38;5;28;01mtry[39;00m:
[0;32m--> 298[0m         [43mfunc[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    299[0m     [38;5;66;03m# this does not capture KeyboardInterrupt, SystemExit,[39;00m
[1;32m    300[0m     [38;5;66;03m# and GeneratorExit[39;00m
[1;32m    301[0m     [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m [38;5;28;01mas[39;00m exc:

File [0;32m/opt/conda/envs/science/lib/python3.10/site-packages/matplotlib/animation.py:924[0m, in [0;36mAnimation._stop[0;34m(self, *args)[0m
[1;32m    922[0m     [38;5;28mself[39m[38;5;241m.[39m_fig[38;5;241m.[39mcanvas[38;5;241m.[39mmpl_disconnect([38;5;28mself[39m[38;5;241m.[39m_resize_id)
[1;32m    923[0m [38;5;28mself[39m[38;5;241m.[39m_fig[38;5;241m.[39mcanvas[38;5;241m.[39mmpl_disconnect([38;5;28mself[39m[38;5;241m.[39m_close_id)
[0;32m--> 924[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mevent_source[49m[38;5;241;43m.[39;49m[43mremove_callback[49m([38;5;28mself[39m[38;5;241m.[39m_step)
[1;32m    925[0m [38;5;28mself[39m[38;5;241m.[39mevent_source [38;5;241m=[39m [38;5;28;01mNone[39;00m

[0;31mAttributeError[0m: 'NoneType' object has no attribute 'remove_callback'

